export const PATH = {
	admin: "/admin",
	cars: "/cars",
	carCreate: "/cars/new",
	carDetail: "/cars/:id",
	clients: "/clients",
	clientCreate: "/clients/new",
	clientDetail: "/clients/:id",
	login: "/login",
	passwordRecovery: "/password_recovery",
  services: "/services",
	serviceCreate: "/services/new",
	serviceDetail: "/services/:id",
	serviceReport: "/",
	users: "/users",
	userCreate: "/users/new",
	userDetail: "/users/:id",
};